apiVersion: v1
kind: Namespace
metadata:
  name: postgres-ns
  labels:
    app: postgresql
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgres    #namespace: postgres-ns
type: Opaque
data:
  password: SihIQVtHdWlWWStecCg=
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-pvc
  namespace: postgres-ns
  labels:
    app: postgresql
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: postgres-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
      - name: postgres-pv
        persistentVolumeClaim:
          claimName: postgresql-pvc 
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: chain-between-db-001
              value: chain-between-postgres-001
            - name: POSTGRES_USER
              value: ingest
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-pv
              mountPath: /var/lib/postgresql/data
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: postgres-ns
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
